# Dependencies
highlighter: rouge
pretty: filename.markdown

plugins:
  - jekyll-default-layout

sass:
  sass_dir:  /docs/_sass
  
include:
 - r.md
 - r2.md

defaults:
  values:
    title: "test title"