files:
  - source: /chrome/locale/en/*.*
    translation: /chrome/locale/%two_letters_code%/%original_file_name%
    escape_special_characters: 0
  - source: /_locales/en/*.json
    translation: /_locales/%two_letters_code%/%original_file_name%
    escape_special_characters: 0
